# Generated by Django 4.1.7 on 2023-03-18 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=20, unique=True)),
                ('service', models.CharField(choices=[('subscribers', 'subscribers')], max_length=50)),
                ('channelName', models.CharField(max_length=150)),
                ('no_of_views', models.BigIntegerField()),
                ('desiredViewersCount', models.BigIntegerField()),
                ('joinDelay', models.IntegerField()),
                ('totalCharge', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
