# Generated by Django 4.1.7 on 2023-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_twitchorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='depositId',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='twitchorder',
            name='apiOrderId',
            field=models.CharField(default=-1, max_length=100),
        ),
        migrations.AddField(
            model_name='twitchorder',
            name='formalCharge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitchorder',
            name='isJoinDelay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchorder',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitchorder',
            name='viewsDone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
