# Generated by Django 4.1.7 on 2023-03-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0003_paymentdetail_depositid_twitchorder_apiorderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
