# Generated by Django 4.1.7 on 2023-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_twitchorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchorder',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
