# Generated by Django 4.1.7 on 2023-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0005_alter_twitchorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='depositId',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
