# Generated by Django 4.1.7 on 2023-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0006_alter_paymentdetail_depositid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchorder',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
