# Generated by Django 4.1.7 on 2023-03-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0007_alter_twitchorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchorder',
            name='service',
        ),
    ]
